CREATE TABLE T_DOCTOR (ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
                       NAME VARCHAR(255) NOT NULL, 
                       SURNAME VARCHAR(255) NOT NULL,
                       PATRONYMIC VARCHAR(255) NOT NULL,
                       SPECIALISATION VARCHAR(255) NOT NULL);
CREATE TABLE T_PATIENT (ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
                       NAME VARCHAR(255) NOT NULL, 
                       SURNAME VARCHAR(255) NOT NULL,
                       PATRONYMIC VARCHAR(255) NOT NULL,
                       PHONE VARCHAR(255) NOT NULL);
CREATE TABLE T_PRESCRIPTION (ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
                       DESCRIPTION VARCHAR(255) NOT NULL, 
                       DOCTOR_ID BIGINT NOT NULL,
                       PATIENT_ID BIGINT NOT NULL,
                       ISSUE_DATE DATE NOT NULL,
                       VALID_DATE DATE NOT NULL,
                       PRIORITY INTEGER NOT NULL,
                       CONSTRAINT DOC_REF FOREIGN KEY(DOCTOR_ID) REFERENCES T_DOCTOR(ID),
                       CONSTRAINT PAT_REF FOREIGN KEY(PATIENT_ID) REFERENCES T_PATIENT(ID));